version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path: ./target/home-inc-api-0.0.1-SNAPSHOT.jar
  
  publish-oas3-docs:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:OF4nvq7zHiuMJJX4Z9smpQ+Es6cMpOQuOXtIML+w9xY"
      - run:
          name: Publishing Open API Specifications
          command: |
            echo "Hi George!"
            echo $CIRCLE_BRANCH
            npx redoc-cli bundle -o ./src/main/resources/static/api.html ./src/main/resources/openapi.yaml

      - store_artifacts:
          path: ./src/main/resources/static


workflows:
  build_test_and_publish: 
    jobs:
      - build-and-test
      - publish-oas3-docs
