version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  
  publish-oas3-docs:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run:
          name: Publishing Open API Specifications
          command: npx redoc-cli bundle -o ./src/main/resources/static/api.html ./src/main/resources/openapi.yaml
      
      - store_artifacts:
          path: ./src/main/resources/static


workflows:
  build_test_and_publish: 
    jobs:
      - build-and-test
      - publish-oas3-docs
