CREATE TABLE payment_types(
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    user_id INTEGER NOT NULL,
    insertDateTime TIMESTAMP NOT NULL DEFAULT NOW(),
    updateDateTime TIMESTAMP,
    FOREIGN KEY user_id REFERENCES users(id)
);

CREATE SEQUENCE se_payment_types
START WITH 8
INCREMENT BY 1;