CREATE TABLE cors(
    id INTEGER NOT NULL PRIMARY KEY,
    allowedOrigin VARCHAR(144) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    insertDateTime TIMESTAMP NOT NULL DEFAULT NOW(),
    updateDateTime TIMESTAMP
);

CREATE SEQUENCE se_cors
START WITH 1
INCREMENT BY 1;