CREATE TABLE cors(
    id INTEGER NOT NULL PRIMARY KEY,
    allowed_origin VARCHAR(144) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    insert_date_time TIMESTAMP NOT NULL DEFAULT NOW(),
    update_date_time TIMESTAMP
);

CREATE SEQUENCE se_cors
START WITH 1
INCREMENT BY 1;